/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encryptor;

import javax.swing.UIManager;

/**
 *
 * @author sweer
 */
public class encInt extends javax.swing.JFrame {

    /**
     * Creates new form encInt
     */
    public encInt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        inL = new javax.swing.JLabel();
        outL = new javax.swing.JLabel();
        keyL = new javax.swing.JLabel();
        inF = new javax.swing.JTextField();
        outF = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        binf = new javax.swing.JButton();
        ext = new javax.swing.JLabel();
        bout = new javax.swing.JButton();
        genKey = new javax.swing.JButton();
        sKey = new javax.swing.JButton();
        prog = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        relay = new javax.swing.JTextArea();
        encB = new javax.swing.JButton();
        decB = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encrptor");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(null);
        setLocationByPlatform(true);
        setMinimumSize(getPreferredSize());
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        inL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        inL.setText("File to Encrypt/Decrypt: ");

        outL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        outL.setText("Output: ");

        keyL.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        keyL.setText("Encryption Key: ");

        inF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        outF.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        binf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        binf.setText("Browse");

        bout.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bout.setText("Browse");

        genKey.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        genKey.setText("Generate");

        sKey.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sKey.setText("Save");

        prog.setForeground(new java.awt.Color(0, 202, 47));

        relay.setEditable(false);
        relay.setColumns(20);
        relay.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        relay.setRows(5);
        jScrollPane1.setViewportView(relay);

        encB.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        encB.setForeground(new java.awt.Color(255, 0, 0));
        encB.setText("Encrypt");

        decB.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        decB.setForeground(new java.awt.Color(0, 200, 0));
        decB.setText("Decrypt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(inL)
                        .addGap(18, 18, 18)
                        .addComponent(inF, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(binf))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(829, 829, 829)
                        .addComponent(ext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(outL, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(outF, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(keyL)
                        .addGap(78, 78, 78)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(genKey, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(sKey))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(encB)
                        .addGap(69, 69, 69)
                        .addComponent(decB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(binf)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inL)
                            .addComponent(inF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(ext)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bout)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outL)
                            .addComponent(outF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(genKey)
                    .addComponent(sKey)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keyL)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encB)
                    .addComponent(decB))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){
            
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new encInt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton binf;
    private javax.swing.JButton bout;
    private javax.swing.JButton decB;
    private javax.swing.JButton encB;
    private javax.swing.JLabel ext;
    private javax.swing.JButton genKey;
    private javax.swing.JTextField inF;
    private javax.swing.JLabel inL;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel keyL;
    private javax.swing.JTextField outF;
    private javax.swing.JLabel outL;
    private javax.swing.JProgressBar prog;
    private javax.swing.JTextArea relay;
    private javax.swing.JButton sKey;
    // End of variables declaration//GEN-END:variables
}
